apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: ghcr.io/pekk4/devopswithkubernetes-todo_app:1.5
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8000"
