apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pingpong-log-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pingpong-log-pv
  storageClassName: pingpong-log-pv
